name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-server-startup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Start server in the background
        run: |
          uvicorn server:app --port 8000 --host 0.0.0.0 &
          # Wait a few seconds to ensure the server is up
          sleep 5

      - name: Check server health
        run: |
          curl -f http://127.0.0.1:8000 || exit 1

      - name: Kill server
        run: |
          pkill uvicorn
